### ISSUE TITLE
Server does not accept callback for `listen` invocation

### ISSUE THREAD

**Issue by benkroeger** [hobbyquaker/binrpc#7]
the package [homematic-xmlrpc](https://github.com/hobbyquaker/homematic-xmlrpc) allows developers to provide a `callback` function [in it's constructor](https://github.com/hobbyquaker/homematic-xmlrpc/blob/master/lib/server.js#L23) which then gets invoked when server is actually listening. (also available [via factory](https://github.com/hobbyquaker/homematic-xmlrpc/blob/master/lib/xmlrpc.js#L47))

I was wondering if anything speaks against implementing the same here as well... esp. since this package aims for being a drop-in replacement.
Happy to provide PR as well.

**Comment by hobbyquaker** [comment]
I'd be happy to merge a PR :-)
